"""asAgent Knowledge package."""

from asagent.knowledge.augmenter import (
    KnowledgeAugmentedPrompt,
    KnowledgeContextAugmenter,
)
from asagent.knowledge.chunker import (
    CHUNKER_VERSION,
    chunk_document,
)
from asagent.knowledge.embedder import (
    DEFAULT_EMBEDDING_DIMENSION,
    DEFAULT_EMBEDDING_MODEL,
    DEFAULT_EMBEDDING_REVISION,
    DEFAULT_QDRANT_COLLECTION,
    LocalMiniLMEmbedder,
    create_pending_embeddings_for_chunks,
    ensure_default_profile,
    generate_point_id,
)
from asagent.knowledge.indexer import (
    IndexSourceStats,
    KnowledgeIndexer,
)
from asagent.knowledge.models import (
    ChunkStatus,
    DocumentFileType,
    DocumentStatus,
    EmbeddingStatus,
    IndexJobKind,
    IndexJobStatus,
    IndexProfileStatus,
    KnowledgeChunk,
    KnowledgeChunkEmbedding,
    KnowledgeCitation,
    KnowledgeDocument,
    KnowledgeIndexJob,
    KnowledgeIndexProfile,
    KnowledgeLibrary,
    KnowledgeRetrievalHit,
    KnowledgeSource,
    LibraryStatus,
    SourceScanStatus,
    SourceStatus,
    normalize_library_name,
)
from asagent.knowledge.parser import (
    PARSER_VERSION,
    ParsedDocument,
    ParsedSection,
    parse_docx,
    parse_file,
    parse_html,
    parse_markdown,
    parse_pdf,
    parse_text,
)
from asagent.knowledge.repository import KnowledgeRepository
from asagent.knowledge.retriever import (
    KnowledgeRetriever,
    RetrievalResult,
)
from asagent.knowledge.scanner import (
    ScannedFile,
    scan_directory,
)
from asagent.knowledge.service import (
    DuplicateLibraryNameError,
    DuplicateSourceError,
    InvalidSourcePathError,
    KnowledgeError,
    KnowledgeLibraryService,
    LastLibraryDeletionError,
    LibraryNotFoundError,
    SourceNotFoundError,
)
from asagent.storage.qdrant import (
    KnowledgeVectorStore,
    VectorPoint,
    VectorSearchResult,
)

__all__ = [
    "CHUNKER_VERSION",
    "ChunkStatus",
    "DEFAULT_EMBEDDING_DIMENSION",
    "DEFAULT_EMBEDDING_MODEL",
    "DEFAULT_EMBEDDING_REVISION",
    "DEFAULT_QDRANT_COLLECTION",
    "DocumentFileType",
    "DocumentStatus",
    "DuplicateLibraryNameError",
    "DuplicateSourceError",
    "EmbeddingStatus",
    "IndexJobKind",
    "IndexJobStatus",
    "IndexProfileStatus",
    "IndexSourceStats",
    "InvalidSourcePathError",
    "KnowledgeAugmentedPrompt",
    "KnowledgeChunk",
    "KnowledgeChunkEmbedding",
    "KnowledgeCitation",
    "KnowledgeContextAugmenter",
    "KnowledgeDocument",
    "KnowledgeError",
    "KnowledgeIndexJob",
    "KnowledgeIndexProfile",
    "KnowledgeIndexer",
    "KnowledgeLibrary",
    "KnowledgeLibraryService",
    "KnowledgeRepository",
    "KnowledgeRetrievalHit",
    "KnowledgeRetriever",
    "KnowledgeSource",
    "KnowledgeVectorStore",
    "LastLibraryDeletionError",
    "LibraryNotFoundError",
    "LibraryStatus",
    "LocalMiniLMEmbedder",
    "PARSER_VERSION",
    "ParsedDocument",
    "ParsedSection",
    "RetrievalResult",
    "ScannedFile",
    "SourceNotFoundError",
    "SourceScanStatus",
    "SourceStatus",
    "VectorPoint",
    "VectorSearchResult",
    "chunk_document",
    "create_pending_embeddings_for_chunks",
    "ensure_default_profile",
    "generate_point_id",
    "normalize_library_name",
    "parse_file",
    "parse_docx",
    "parse_html",
    "parse_markdown",
    "parse_pdf",
    "parse_text",
    "scan_directory",
]
